<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>2c648a2e-6774-409f-a7b8-e9b69de5f213</UserSecretsId>
	  <!--<GenerateDocumentationFile>true</GenerateDocumentationFile>-->
	  <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json~RF3851aec.TMP" />
    <None Remove="Controllers\LoginController.cs~RF2efe143.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.28.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FreakyFashionClient\FreakyFashionClient.csproj" />
    <ProjectReference Include="..\RepositoriesDependencyInjectionProject\RepositoriesDependencyInjectionProject.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PaginationInterfaces\" />
  </ItemGroup>

</Project>
