<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Controllers\HomeController.cs~RF1d9da75.TMP" />
    <None Remove="Services\ManageProductService.cs~RF28a8a64.TMP" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\logotype.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationLayer\ApplicationLayer.csproj" />
  </ItemGroup>

</Project>
