trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  #Service Connection to private cloud components
  #azureSubscriptionConnection: 'MyDockerRegistryConnection'

  # ACR login server!
  azureContainerRegistry: 'acrfreakyfashionapizy.azurecr.io'

  #Docker image will use this repo inside Azure container registry.
  imageRepository: 'freakyfashionapi'

  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: 'Build and Push Docker Image Stage'
  jobs:
  - job: Build
    displayName: 'Compile and Containerize Web API'
    steps:

    # Step 1: Build the .NET 10 Docker image
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        containerRegistry: 'MyDockerRegistryConnection'
        repository: '$(imageRepository)'
        dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
        tags: |
          $(tag)
          latest
        arguments: '--build-arg REGISTRY=://microsoft.com'

    #Push the image layers to your registry
    - task: Docker@2
      displayName: 'Push Image to Azure Container Registry'
      inputs:
        command: 'push'
        containerRegistry: 'MyDockerRegistryConnection'
        repository: '$(imageRepository)'
        tags: |
          $(tag)
          latest