<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Dto\DtoCategory.cs~RF1866b63.TMP" />
    <None Remove="Dto\DtoOrder.cs~RF33a271e.TMP" />
    <None Remove="Dto\ProductUploadForm.cs~RF161173c.TMP" />
    <None Remove="Interfaces\IGenericRepository.cs~RF9b4d43.TMP" />
    <None Remove="Interfaces\IMapper.cs~RF7d85ba.TMP" />
    <None Remove="Interfaces\IOrderItemRepository.cs~RF33cf774.TMP" />
    <None Remove="IStorageContainerServices\IAzureBlobService.cs~RF67560a.TMP" />
    <None Remove="Services\OrderService.cs~RF29dc482.TMP" />
    <None Remove="UserManagerResponse.cs~RF2fc66d4.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DomainLayer\DomainLayer.csproj" />
  </ItemGroup>

</Project>
