<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Repositories\CategoryRepository.cs~RF11feee0.TMP" />
    <None Remove="Repositories\GenericRepository.cs~RF6b3cd1.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.28.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationLayer\ApplicationLayer.csproj" />
    <ProjectReference Include="..\DomainLayer\DomainLayer.csproj" />
  </ItemGroup>

</Project>
